### PR TITLE
Completely reworked the library code making it more Object Oriented

### PR DESCRIPTION
**Pull request by FoxWorn3365**
I improved the code of this library by writing it virtually from scratch and thus making it newer, more reliable, and clearer.
Thanks to the introduction of ReactPHP as an optional library, I was able to include full support for webhooks and being non-blocking it can easily be integrated with other libraries that require other code to run while doing so (such as DiscordPHP).
Implementing a simple cache manager reduces the number of requests that are made to top.gg and thus the danger of being rate-limited is removed.
The new library is fully documented in the `docs.md` file with various examples, plus it includes internal error handling, removing thoughts from developers being that to handle an exception it will suffice to enter a specific function at the beginning of the code.
In addition, thanks to the implementation of objects, it will be easier to use and may also bring new people closer to the library (maybe).
That said, I remain available for any questions or to suggest changes.
Thank you :D

### CODE REVIEW

**Comment by FoxWorn3365** [comment]
Added guild support, updated Documentation for guild support

**Comment by pixxies** [comment]
Does this have breaking changes? It wouldn't be reasonable to deploy an update that breaks anyone's existing code since the API itself hasn't changed.

Scraping guild pages is also not recommended.

**Comment by FoxWorn3365** [comment]
I have removed the Guild integration due to several suggestions by moderators and users of the Top.gg's Discord Server.
Anyways this have breaking changes but there are several reasons that support this library:
* Is Object Oriented and handles everything with objects, so it is easier to use and takes up less Ram
* I have implemented an automatic caching system so as to avoid flooding of requests to your API, the current library does not handle this scope
* Integrates webhooks asynchronously with ReactPHP so that it can also be used, for example, in conjunction with an instance of DiscordPHP
* It is more compact and lighter
* Manages exceptions internally so that the user decides which ones to handle and which ones not to handle

For other questions i'm always here

Thank you for your time.
- FoxWorn3365

**Comment by FoxWorn3365** [comment]
(However a small addition: this library has not been updated for more than a year and a half, I think renewing it a little bit is not a bad idea)

**Comment by pixxies** [comment]
I appreciate your time and effort but this is probably better off as a third-party library. There have been no changes to our API that would justify pushing out breaking changes.

I still think your work would be useful as an alternative to this one though so people have the option. Feel free to offer it as a third-party sdk! 🙏

**Comment by FoxWorn3365** [comment]
I fully understand, I will post my library.

Just to ask for confirmation from you as well, is using the search API to retrieve information regarding servers just strongly discouraged or does it go against ToS and risk something?

Said that I think that this PR can be closed

**Comment by pixxies** [comment]
Yes that's against TOS since it's technically site scraping and not a supported public API.

**Comment by FoxWorn3365** [comment]
Perfect, thank you so much for your reply, this way I will avoid getting into trouble with you 😄

Said that maybe if you have time I have one question before I/you will close the PR:
A user suggested that *maybe* when I develop the new library for Top.gg I could add it to the documentation as a "suggestion" but just I ask because neither of us were sure.
Thanks in advance 👍

**Comment by pixxies** [comment]
We don't promote any third-party SDKs in our official documentation. You are free to use "Top.gg" and Top.gg-related tags on your GitHub repository though as long as you also include a clear disclaimer at the top of your readme file and documentation homepage saying your SDK is an unofficial one.

**Comment by FoxWorn3365** [comment]
Understood everything, thanks again for the answers.

I wish you a good evening 👋

**Pull request closed without merging**
